# CMake generated Testfile for 
# Source directory: /users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib
# Build directory: /users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeLib.testArgumentParser "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties(CMakeLib.testArgumentParser PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestBinPacker "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties(CMakeLib.testCTestBinPacker PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceAllocator "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties(CMakeLib.testCTestResourceAllocator PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceSpec "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib")
set_tests_properties(CMakeLib.testCTestResourceSpec PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceGroups "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties(CMakeLib.testCTestResourceGroups PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testGeneratedFileStream "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties(CMakeLib.testGeneratedFileStream PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRST "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testRST" "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib")
set_tests_properties(CMakeLib.testRST PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRange "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties(CMakeLib.testRange PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testOptional "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties(CMakeLib.testOptional PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testString "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties(CMakeLib.testString PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testStringAlgorithms "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties(CMakeLib.testStringAlgorithms PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testSystemTools "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties(CMakeLib.testSystemTools PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUTF8 "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties(CMakeLib.testUTF8 PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLParser "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties(CMakeLib.testXMLParser PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLSafe "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties(CMakeLib.testXMLSafe PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testFindPackageCommand "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties(CMakeLib.testFindPackageCommand PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVProcessChain "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties(CMakeLib.testUVProcessChain PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVRAII "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties(CMakeLib.testUVRAII PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVStreambuf "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/bin/cmake")
set_tests_properties(CMakeLib.testUVStreambuf PROPERTIES  _BACKTRACE_TRIPLES "/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;60;add_test;/users/HenryXu/cuda/cutlass/cmake-3.16.0-rc4/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
